@startuml
actor User as user
boundary QtFrame as qt_frame
entity "/camera_node_let_manager" as slam_cloud

user -> qt_frame: Start()
activate qt_frame
alt Received Message
	slam_cloud -> qt_frame: [image]
	qt_frame -> qt_frame: display(image)
	qt_frame -> user: Image
else timeout
	qt_frame -> qt_frame: skip()
	qt_frame -[#red]> user:  No data received
	deactivate qt_frame
end
@enduml
